services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    env_file:
      - db.env
    networks:
      - proxy-tier

  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    networks:
      - proxy-tier
    expose:
      - 80
    volumes:
      - wp_data:/var/www/html
      - ./bootstrap.sh:/docker-entrypoint-initwp.d/bootstrap.sh:ro
    env_file:
      - wp.env
    entrypoint: [ "bash", "/var/www/html/entrypoint.sh" ]

volumes:
  db:
  wp_data:


networks:
  proxy-tier:
    external: true
